// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qnmafrxhrqdeqolztran.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFubWFmcnhocnFkZXFvbHp0cmFuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkxMjUwMTIsImV4cCI6MjA2NDcwMTAxMn0.CvHFzxYRg11bEe-GTILpAxfcqFlnwtNIym1_usYcCUo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);